### ISSUE TITLE
Lost kingdom chronicles undefined

### ISSUE THREAD

**Issue by robin-debry** [nusco/algosup-cyoa#2]
When you go on Engage in conversation and ask where is the nearest city 
I have this :
<img width="809" alt="Screenshot 2024-02-12 at 11 08 35" src="https://github.com/nusco/algosup-cyoa/assets/91249812/bdef1550-7469-4974-b0d3-bd6ab4f339bc">

If we click on undefined the game crash

**Comment by nusco** [comment]
Wrong repo! This should go to the Kingdom's citizens.
